<h2>Problem Statement:</h2>
Given a NumPy array of integers, return an array of unique elements in sorted order.

In [3]:
import numpy as np
arr = np.array([4, 2, 2, 8, 4, 3, 3, 1])
np.unique(arr)

array([1, 2, 3, 4, 8])

<h2>Problem Statement:</h2>
Given a NumPy array, replace all values greater than twice the mean with the mean itself.

<h3 style="color: Brown;">Modifying Elements Using Boolean Indexing:</h3>
<h5 style="color: blue;">arr[arr > ___ ]</h5>



In [16]:
import numpy as np

arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)
for i in range(len(arr)):
    if arr[i] > mean_value:
      arr[i] = mean_value
print(arr)

[ 1  2  3 45  5  6 45]


In [19]:
arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)
for idx, value in enumerate(arr):
    if value > mean_value:
        arr[idx] = mean_value
print(arr)



[ 1  2  3 45  5  6 45]


In [17]:
arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)
threshold = mean_value * 2 
arr[arr > threshold] = mean_value 
print(arr)

[ 1  2  3 45  5  6 45]


In [18]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 2] = 10  # Replace elements > 2 with 10
print(arr)

[ 1  2 10 10 10]
