In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
even = arr[arr % 2 == 0]
print(even)


[2 4 6 8]


In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
product = np.dot(a,b)
vertical_stack = np.vstack((a,b))
hori_stack = np.hstack((a,b))
print(product)


print(vertical_stack)
print(hori_stack)

[[19 22]
 [43 50]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [20]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print((np.mean(arr)))
print((np.std(arr)))
print((np.median(arr)))

5.5
2.8722813232690143
5.5


In [21]:
arr = np.array([1, 2, np.nan, 4])
print(np.isnan(arr))

[False False  True False]


<h1>Normalizing Array</h1>

Normalizing an array means scaling its values to a specific range, usually to make data easier to compare or process. Common normalization techniques include:

Min-Max Normalization:
Scales values between 0 and 1 (or any custom range).

In [23]:
import numpy as np
X = np.array([10, 20, 30, 40, 50])
norm = (X-X.min())/(X.max() - X.min())
print(norm)

[0.   0.25 0.5  0.75 1.  ]


<h2>Problem Statement:</h2>
Given a NumPy array, replace all values with the mean itself.

In [41]:
import numpy as np

arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)

for i in range(len(arr)):
#range expects an integer value for the length of the iteration
    arr[i] = mean_value
print(arr)


[45 45 45 45 45 45 45]


In [42]:
import numpy as np
arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)

for idx, value in enumerate(arr):
    if value > mean_value:
        arr[idx] = mean_value 
print(arr)


[ 1  2  3 45  5  6 45]


<h2>Problem Statement:</h2>
Given a NumPy array, replace all values greater than twice the mean with the mean itself.

In [46]:
import numpy as np

arr = np.array([1, 2, 3, 100, 5, 6, 200])
mean_value = np.mean(arr)
#define a threshold
threshold = mean_value * 2
arr[arr > threshold] = mean_value
print(arr)

[ 1  2  3 45  5  6 45]
