<h1>1. Single Element Indexing</h1>




In [1]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])
# Output: 20 (row 0, column 1)
print(arr[0, 1]) 


20


 <h1>2.Slicing and Striding</h1>

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1:4]

array([2, 3, 4])

In [3]:
#after index 1 to 8 with gap of 2
arr[1:8:2]

array([2, 4, 6, 8])

In [4]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#reversing the array
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [6]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr.ndim)

2


→ Select rows from the start (index 0) up to index 2 (not including index 2).
This means we take the first two rows

→ Select columns from index 1 onward (till the end).
This means we take columns 1 and 2 (20, 30 in the first row and 50, 60 in the second row).


In [10]:
arr[:2,1:]

array([[20, 30],
       [50, 60]])

In [ ]:
arr = np.array([1, 2, 3])
arr.shape

#arr.shape returns the shape (dimensions) of the NumPy array.
#Since arr = np.array([1, 2, 3]) is a 1D array with 3 elements, its shape is (3,).
#The comma in (3,) indicates that it's a 1D array, not a 2D or higher-dimensional array.

(3,)