**Intrinsic NumPy Array Creation Functions 🚀

NumPy provides built-in functions for creating arrays, categorized by their dimensions:

1D Arrays (Vectors)

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(5)
arr11 = np.arange(2, 3, 0.1)
#print from 2 to 3 with 0.1 difference 
print(arr1,arr11)

[0 1 2 3 4] [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [3]:
# start , end , number to generate 
arr2 = np.linspace(1,10,4)
print(arr2)

[ 1.  4.  7. 10.]


In [4]:
arr2.astype(int)
#or 
arr2 = np.linspace(1,10,4, dtype = int )
print(arr2)


[ 1  4  7 10]


In [5]:
arr3 = np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [6]:
#number of values to be given(4), value(5)
arr4 = np.full(4,5)
print(arr4)

[5 5 5 5]


In [7]:
arr5 = np.ones(7)
print(arr5)

[1. 1. 1. 1. 1. 1. 1.]


2️⃣ 2D Arrays (Matrices)


In [8]:
arr6 =np.eye(3)
#Creates a 3×3 identity matrix (diagonal ones, rest zeros)
print(arr6, "\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [9]:
arr7 = np.ones((3,4))
#creates matrix of 1s 3x4
print(arr7)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
arr8 = np.zeros((2,3))
print(arr8)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr9 = np.full((2,3),10)
#print a 2x3 matrix of value 10.
print(arr9)

[[10 10 10]
 [10 10 10]]


In [20]:
arr10 = [[1,2,3], [4,5,6]]
print(arr10)



[[1, 2, 3], [4, 5, 6]]


In [21]:
diagonal_values = np.diag(arr10)
print(diagonal_values)

[1 5]


In [22]:
arr11 = np.diag((2,3,4), k =1)
print(arr11)

[[0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]
 [0 0 0 0]]


In [23]:
arr12 = np.diag((2,3,4), k = -1)
print(arr12)

[[0 0 0 0]
 [2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]]


✅ Here, k=1 moves the diagonal one position above the main diagonal.

✅ If k=-1, the diagonal moves one position below.

3️⃣ ndarrays (Multi-Dimensional Arrays)

In [24]:
arr13 = np.linspace(2,10, 5)
print(arr13)

[ 2.  4.  6.  8. 10.]


# Vandermonde Matrix in NumPy

The **Vandermonde matrix** is a matrix where each row corresponds to a geometric progression of a given sequence of numbers.

### Formula:
For a given input array **x** and number of columns **N**, the Vandermonde matrix **V** is defined as:

\[
V(i, j) = x_i^{(N-j-1)}
\]

where:
- \( x_i \) are the input values.
- \( N \) is the number of columns.
- The powers decrease from left to right.


In [25]:
np.vander((arr13), 2)

array([[ 2.,  1.],
       [ 4.,  1.],
       [ 6.,  1.],
       [ 8.,  1.],
       [10.,  1.]])

In [26]:
np.vander((arr13), 3)

array([[  4.,   2.,   1.],
       [ 16.,   4.,   1.],
       [ 36.,   6.,   1.],
       [ 64.,   8.,   1.],
       [100.,  10.,   1.]])

In [28]:
np.vander((arr13), 4)

array([[   8.,    4.,    2.,    1.],
       [  64.,   16.,    4.,    1.],
       [ 216.,   36.,    6.,    1.],
       [ 512.,   64.,    8.,    1.],
       [1000.,  100.,   10.,    1.]])

In [ ]:
np.diag([1,2,3])

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [40]:
np.diag([1,2,3],1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [41]:
np.diag([1,2,3], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [46]:
np.diag([9,2,1], k = -1)

array([[0, 0, 0, 0],
       [9, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0]])

<h1><b>3 - General ndarray Creation Functions</b></h1>


In [62]:
a = np.zeros((2,3, 2))

In [61]:
print(a.ndim)

3


In [63]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])

7
