Array creation : Conversion from other python structures 
a list of numbers will create a 1D array,

a list of lists will create a 2D array,

further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.


In [1]:
import numpy as np 

In [ ]:
#2-D array
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
listarray.dtype 

dtype('int32')

In [6]:
listarray.shape 

(3, 3)

In [7]:
np.array({34,23,33})

array({33, 34, 23}, dtype=object)

making object is not efficient. 
Generally make array of float or integer 


In [12]:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [13]:
#a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [14]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
#tells the dimension of the array
print(arr.ndim)

3
